# Generated by Django 4.1.2 on 2022-11-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pac_icon', models.CharField(max_length=100)),
                ('pac_title', models.CharField(max_length=100)),
                ('pac_desc', models.TextField()),
            ],
        ),
    ]
