# Generated by Django 4.1.2 on 2022-11-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whereTo', models.CharField(max_length=100)),
                ('howmany', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('leaveingdate', models.CharField(max_length=100)),
            ],
        ),
    ]
